# Generated by Django 2.1.2 on 2018-11-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progress',
            field=models.TextField(default='hola'),
            preserve_default=False,
        ),
    ]
