export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL_LOGIN = 'AUTH_FAIL_LOGIN';
export const AUTH_FAIL_SIGNUP = 'AUTH_FAIL_SIGNUP';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PROFILE_START = 'PROFILE_START';
export const PROFILE_LOADED = 'PROFILE_LOADED';
