# Generated by Django 2.1.2 on 2018-11-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('teaching', models.CharField(max_length=25)),
                ('description_language', models.CharField(max_length=25)),
                ('words', models.TextField()),
                ('owner', models.CharField(max_length=120)),
            ],
        ),
    ]
