# Generated by Django 2.0.9 on 2018-11-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
    ]
